apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: carts-canary
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts
  type: ClusterIP
status:
  loadBalancer: {}
